org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
org.gradle.cache.cleanup = false

group = fi.dy.masa
mod_id = malilib
mod_name = MaLiLib
author = masa
mod_file_name = malilib-fabric

# Current mod version
mod_version = 0.29.99-dev

# Minecraft, Fabric Loader and API and mappings versions
minecraft_version_out = 26.3-pre-2
minecraft_version = 26.3-pre-2

fabric_loader_version = 0.19.5
mod_menu_version = 20.0.1
fabric_api_version = 0.159.4+26.3

iris_version = 1.11.2
iris_mc_version = 26.2
conditionalmixin_version = 0.6.4
