org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
org.gradle.cache.cleanup = false

group = fi.dy.masa
mod_id = malilib
mod_name = MaLiLib
author = masa
mod_file_name = malilib-fabric

# Current mod version
mod_version = 0.24.49-dev

# Minecraft, Fabric Loader and API and mappings versions
minecraft_version_out = 25w18a
minecraft_version = 25w18a
mappings_version = 25w18a+build.6

fabric_loader_version = 0.16.14
mod_menu_version = 14.0.0-rc.2
iris_version = 1.8.11
fabric_api_version = 0.122.0+1.21.6
