org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
org.gradle.cache.cleanup = false

group = fi.dy.masa
mod_id = malilib
mod_name = MaLiLib
author = masa
mod_file_name = malilib-fabric

# Current mod version
mod_version = 0.26.99-dev

# Minecraft, Fabric Loader and API and mappings versions
minecraft_version_out = 25w46a
minecraft_version = 25w46a
mappings_version = 25w46a+build.3

fabric_loader_version = 0.17.3
mod_menu_version = 16.0.0-rc.1
iris_version = 1.9.6
iris_mc_version = 1.21.10
fabric_api_version = 0.138.4+1.21.11
