package fi.dy.masa.malilib.util.input;

import javax.annotation.Nullable;

public enum KeyState
{
	// Keyboard
	KEY_PRESSED,
	KEY_RELEASED,
	KEYMAP_CHANGED,

	// Text Box
	TEXT_EDIT,
	TEXT_INPUT,

	// Mouse
	MOUSE_MOVED,
	MOUSE_PRESSED,
	MOUSE_RELEASED,
	MOUSE_SCROLLED,

	// File Drop
	DROP_FILE,
	DROP_TEXT,
	DROP_START,
	DROP_FINISH,
	DROP_POSITION,

	// Gamepad
	GAMEPAD_AXIS_MOTION,
	GAMEPAD_BUTTON_DOWN,
	GAMEPAD_BUTTON_UP,
	GAMEPAD_ADDED,
	GAMEPAD_REMOVED,
	GAMEPAD_REMAPPED,
	GAMEPAD_TOUCHPAD_DOWN,
	GAMEPAD_TOUCHPAD_MOTION,
	GAMEPAD_TOUCHPAD_UP,
	GAMEPAD_SENSOR_UPDATE,
	GAMEPAD_UPDATE_COMPLETE,
	GAMEPAD_STEAM_HANDLE_UPDATED,
	;

	@Nullable
	public static KeyState fromEventType(final int eventType)
	{
		return switch (eventType)
		{
			case EventCodes.EVENT_KEY_PRESS -> KEY_PRESSED;
			case EventCodes.EVENT_KEY_RELEASE -> KEY_RELEASED;
			case EventCodes.EVENT_KEYMAP_CHANGED -> KEYMAP_CHANGED;

			case EventCodes.EVENT_TEXT_EDIT -> TEXT_EDIT;
			case EventCodes.EVENT_TEXT_INPUT -> TEXT_INPUT;

			case EventCodes.EVENT_MOUSE_MOVED -> MOUSE_MOVED;
			case EventCodes.EVENT_MOUSE_PRESS -> MOUSE_PRESSED;
			case EventCodes.EVENT_MOUSE_RELEASE -> MOUSE_RELEASED;
			case EventCodes.EVENT_MOUSE_SCROLL -> MOUSE_SCROLLED;

			case EventCodes.EVENT_DROP_FILE -> DROP_FILE;
			case EventCodes.EVENT_DROP_TEXT -> DROP_TEXT;
			case EventCodes.EVENT_DROP_START -> DROP_START;
			case EventCodes.EVENT_DROP_FINISH -> DROP_FINISH;
			case EventCodes.EVENT_DROP_POSITION -> DROP_POSITION;

			case EventCodes.EVENT_GAMEPAD_AXIS_MOTION -> GAMEPAD_AXIS_MOTION;
			case EventCodes.EVENT_GAMEPAD_BUTTON_DOWN -> GAMEPAD_BUTTON_DOWN;
			case EventCodes.EVENT_GAMEPAD_BUTTON_UP -> GAMEPAD_BUTTON_UP;
			case EventCodes.EVENT_GAMEPAD_ADDED -> GAMEPAD_ADDED;
			case EventCodes.EVENT_GAMEPAD_REMOVED -> GAMEPAD_REMOVED;
			case EventCodes.EVENT_GAMEPAD_REMAPPED -> GAMEPAD_REMAPPED;
			case EventCodes.EVENT_GAMEPAD_TOUCHPAD_DOWN -> GAMEPAD_TOUCHPAD_DOWN;
			case EventCodes.EVENT_GAMEPAD_TOUCHPAD_MOTION -> GAMEPAD_TOUCHPAD_MOTION;
			case EventCodes.EVENT_GAMEPAD_TOUCHPAD_UP -> GAMEPAD_TOUCHPAD_UP;
			case EventCodes.EVENT_GAMEPAD_SENSOR_UPDATE -> GAMEPAD_SENSOR_UPDATE;
			case EventCodes.EVENT_GAMEPAD_UPDATE_COMPLETE -> GAMEPAD_UPDATE_COMPLETE;
			case EventCodes.EVENT_GAMEPAD_STEAM_HANDLE_UPDATED -> GAMEPAD_STEAM_HANDLE_UPDATED;

			default -> null;
		};
	}
}
